# -*- coding: utf-8 -*-
"""BBC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qwhW0F1RJdidc1mjzzgoBlyeGaZ88IHu

#Scrapping the HeadLines of Articles  from BBC.com using BeautifulSoup
"""

#importing the required libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime

# URL of the news website you want to scrape
url = 'https://www.bbc.com/news'

# Send a GET request to the URL
response = requests.get(url)

# Parse the HTML content of the webpage
soup = BeautifulSoup(response.text, 'html.parser')
print(soup)

#Title
title=soup.find('title')
print(title)

# Find the current date
current_date = datetime.now().strftime('%Y-%m-%d')

# Find all the headline elements on the webpage
headlines = soup.find_all('h2')  # You might need to adjust the tag based on the structure of the website

# Extract the text from each headline and store it in a list
headline_texts = [headline.text.strip() for headline in headlines[1:12]]
print(headline_texts)

# Create a DataFrame with the headlines and date
df = pd.DataFrame({'Date': [current_date] * len(headline_texts), 'BBC News-Headlines': headline_texts})
print(df)

# Save the DataFrame to a CSV file
df.to_csv('news_headlines.csv', index=False)

print("Headlines saved to 'news_headlines.csv'")
print("Date:", current_date)